site_name: Tabletop Simulator Scripting Documentation
theme:
  name: 'material'
  palette:
    primary: 'indigo'
    accent: 'indigo'
  feature:
    tabs: true
  logo: 'img/Icon-Dice.png'
  favicon: 'img/Icon-Dice.png'
extra_css:
  - css/base.css
markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - toc:
      permalink: true
pages:
  - Getting Started:
    - Introduction: index.md
    - Overview: overview.md
    - Atom: atom.md
    - External Editor API: externaleditorapi.md
  - Lua API:
    - Introduction: luaapi.md
    - Event: event.md
    - Base: base.md
    - Object: object.md
    - AssetBundle : assetbundle.md
